//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Proyecto_EDD.rc
//
#define IDD_MAIN                        101
#define IDR_MAIN_MENU                   103
#define IDD_DIALOG1                     104
#define IDD_REG_APP                     104
#define IDD_QUERY_APP                   105
#define IDD_REG_MED                     106
#define IDD_REG_SPE                     107
#define IDD_REG_PATIENT                 108
#define IDD_REG_APP1                    109
#define IDD_VIEW_APP                    109
#define IDC_COMBO1                      1002
#define IDC_RP_GENDER_COMBO             1002
#define IDC_COMBO2                      1003
#define IDC_RP_BLOOD_COMBO              1003
#define IDC_COMBO3                      1004
#define IDC_RP_FIRSTDR_COMBO            1004
#define IDC_EDIT1                       1005
#define IDC_RS_SPENAME_EDIT             1005
#define IDC_DATETIMEPICKER1             1006
#define IDC_EDIT15                      1006
#define IDC_RA_APPDATE_DTP              1006
#define IDC_RS_SPEDESC_EDIT             1006
#define IDC_DATETIMEPICKER2             1007
#define IDC_EDIT12                      1007
#define IDC_EDIT16                      1007
#define IDC_QA_PID_EDIT                 1007
#define IDC_RA_APPTIME_DTP              1007
#define IDC_RP_FLNAME_EDIT              1007
#define IDC_CHECK1                      1008
#define IDC_EDIT13                      1008
#define IDC_EDIT17                      1008
#define IDC_QA_DRNAME_EDIT              1008
#define IDC_RA_DOUBLEAPP_CHECK          1008
#define IDC_RP_SLNAME_EDIT              1008
#define IDC_COMBO4                      1009
#define IDC_EDIT14                      1009
#define IDC_QA_DRSPE_EDIT               1009
#define IDC_RA_SELMO_COMBO              1009
#define IDC_EDIT2                       1010
#define IDC_COMBO5                      1010
#define IDC_QA_MONTH_COMBO              1010
#define IDC_RP_PHONENUM_EDIT            1010
#define IDC_EDIT3                       1011
#define IDC_COMBO6                      1011
#define IDC_QA_SPE_COMBO                1011
#define IDC_RP_H_EDIT                   1011
#define IDC_EDIT4                       1012
#define IDC_DATETIMEPICKER3             1012
#define IDC_RM_SCHE_FROM_DTP            1012
#define IDC_RP_W_EDIT                   1012
#define IDC_EDIT5                       1013
#define IDC_RM_SCHE_TO_DTP              1013
#define IDC_RP_REFER_EDIT               1013
#define IDC_EDIT6                       1014
#define IDC_PATIENT_BIRTHD_EDIT         1014
#define IDC_EDIT7                       1015
#define IDC_PATIENT_AGE_EDIT            1015
#define IDC_EDIT8                       1016
#define IDC_PATIENT_GENDER_EDIT         1016
#define IDC_EDIT9                       1017
#define IDC_PATIENT_H_EDIT              1017
#define IDC_EDIT10                      1018
#define IDC_PATIENT_W_EDIT              1018
#define IDC_RP_FNAME_EDIT               1018
#define IDC_EDIT11                      1019
#define IDC_PATIENT_BLOOD_EDIT          1019
#define IDC_BUTTON1                     1020
#define IDC_RS_REGSPE_CMD               1020
#define IDC_BUTTON2                     1021
#define IDC_RS_CLEARREG_CMD             1021
#define IDC_BUTTON3                     1022
#define IDC_RS_LOOKSPE_CMD              1022
#define IDC_LIST1                       1023
#define IDC_SPE_LIST                    1023
#define IDC_BUTTON4                     1024
#define IDC_DATETIMEPICKER4             1024
#define IDC_QA_LOOKAPP_CMD              1024
#define IDC_RP_BIRTHD_DTP               1024
#define IDC_BUTTON5                     1025
#define IDC_RM_MON_CHECK                1025
#define IDC_RS_DELETESPE_CMD            1025
#define IDC_BUTTON6                     1026
#define IDC_RM_TUE_CHECK                1026
#define IDC_RP_CLEARREG_CMD             1026
#define IDC_RM_WED_CHECK                1027
#define IDC_RS_LOOKDRINFO_CMD           1027
#define IDC_RM_THU_CHECK                1028
#define IDC_RM_FRI_CHECK                1029
#define IDC_RS_LOOKDRLIST_CMD           1029
#define IDC_RM_GENREPORT_CMD            1030
#define IDC_RM_REGMED_CMD               1031
#define IDC_MAIN_TODAY                  1032
#define IDC_RM_CLEARREG_CMD             1032
#define IDC_MAIN_TIME                   1033
#define IDC_MAIN_USER_FULLNAME          1034
#define IDC_MAIN_USERNAME               1035
#define IDC_QA_ATYPE_COMBO              1036
#define IDC_QA_MO_COMBO                 1037
#define IDC_QA_APP_LIST                 1038
#define IDC_QA_APPCODE_EDIT             1039
#define IDC_QA_WEEK_DTP                 1040
#define IDC_QA_WEEK_DTP2                1041
#define IDC_QA_SEARCHDR_CMD             1042
#define IDC_QA_SEARCHAPP_CMD            1043
#define IDC_QA_CLEARAPP_CMD             1044
#define IDC_QA_MARKAPP_CMD              1045
#define IDC_QA_CANCELAPP_CMD            1046
#define IDC_RA_SELPATIENT_COMBO         1047
#define IDC_RA_SELSPE_COMBO             1048
#define IDC_RA_SELDR_COMBO              1049
#define IDC_RA_DESC_EDIT                1050
#define IDC_RA_PHONENUM_EDIT            1051
#define IDC_PATIENT_NAME_EDIT           1052
#define IDC_DR_NAME_EDIT                1053
#define IDC_DR_PROID_EDIT               1054
#define IDC_RA_ERROR_LOG                1055
#define IDC_DR_IMG                      1056
#define IDC_RA_RESERVEAPP_CMD           1057
#define IDC_RA_CLEARAPP_CMD             1058
#define IDC_RM_DR_FNAME_EDIT            1059
#define IDC_RM_DR_SNAME_EDIT            1060
#define IDC_RM_DR_FLNAME_EDIT           1061
#define IDC_RM_DR_SLNAME_EDIT           1062
#define IDC_RM_PHONENUM_EDIT            1063
#define IDC_RM_PROID_EDIT               1064
#define IDC_RM_GENDER_COMBO             1065
#define IDC_RM_MO_COMBO                 1066
#define IDC_DR_LIST                     1067
#define IDC_RM_BIRTHD_DTP               1068
#define IDC_RM_LOADIMG_CMD              1069
#define IDC_RM_LOOKDR_CMD               1070
#define IDC_RM_DELETEREG_CMD            1071
#define IDC_RP_SNAME_EDIT               1072
#define IDC_PATIENT_LIST                1073
#define IDC_RP_REGPATIENT_CMD           1074
#define IDC_RP_LOOKPATIENT_CMD          1075
#define IDC_RP_DELETEREG_CMD            1076
#define IDC_RP_GENREPORT_CMD            1077
#define IDC_RM_IMGPATH                  1078
#define IDC_RP_ERROR_LOG                1079
#define IDC_RM_ERROR_LOG                1080
#define IDC_RS_ERROR_LOG                1081
#define CMD_REG_MED                     40004
#define CMD_REG_PATIENT                 40005
#define CMD_REG_DOC                     40006
#define CMD_REG_SPE                     40007
#define CMD_REG_APP                     40008
#define CMD_QUERY_APP                   40009
#define CMD_EXIT                        40010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40011
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
